# Dependencies
markdown:     rdiscount
pygments:     true

# Permalinks
permalink:    pretty

# Server
source:       ./docs
destination:  ./_gh_pages
port:         9001

# Custom base urls
baseurl:     /docs/bootstrap/
staticurl:   /docs/bootstrap/assets/
